pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'custom-gradle:6.6.1' // Name of the custom Docker image
        DOCKERFILE_PATH = '03-CICD/Entrega_CICD/Ejercicios_Jenkins/ejercicio_2/gradle.Dockerfile'
        PROJECT_PATH = '03-CICD/Entrega_CICD/Ejercicios_Jenkins/ejercicio_1/jenkins-resources/calculator'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building the custom Gradle Docker image...'
                script {
                    docker.build(env.DOCKER_IMAGE, "-f ${env.DOCKERFILE_PATH} .")
                }
            }
        }

        stage('Compile') {
            agent {
                docker {
                    image "${env.DOCKER_IMAGE}"
                    args '--user root'
                }
            }
            steps {
                echo 'Compiling source code...'
                dir("${env.PROJECT_PATH}") {
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            agent {
                docker {
                    image "${env.DOCKER_IMAGE}"
                    args '--user root'
                }
            }
            steps {
                echo 'Running unit tests...'
                dir("${env.PROJECT_PATH}") {
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
