apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld-replicated
spec:
  selector: 
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        component: backend
    spec:
      volumes:
      - name: data
        emptyDir: {}         
      containers:
      - name: helloworld
        image: eiximenis/go-hello-world
        ports:
          - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
