pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Prepare Environment') {
            steps {
                echo 'Changing to the correct directory...'
                dir('ejercicio_1/jenkins-resources/calculator') {
                    // Ensure `gradlew` has execution permissions
                    sh 'chmod +x ./gradlew'
                }
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling source code...'
                dir('ejercicio_1/jenkins-resources/calculator') {
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running unit tests...'
                dir('ejercicio_1/jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
