pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                echo 'Listing directory contents...'
                sh 'ls -l ejercicio_1/jenkins-resources/calculator'
                sh 'pwd'
            }
        }

        stage('Prepare Environment') {
            steps {
                echo 'Setting permissions for gradlew...'
                sh 'chmod +x ejercicio_1/jenkins-resources/calculator/gradlew'
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling source code...'
                sh './ejercicio_1/jenkins-resources/calculator/gradlew compileJava'
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running unit tests...'
                sh './ejercicio_1/jenkins-resources/calculator/gradlew test'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
