apiVersion: v1
kind: Pod
metadata:
  name: wp
spec:
  containers:
  - name: wp
    image: wordpress
    env: 
    - name: WORDPRESS_DB_HOST
      value: "10.96.74.204"
    - name: WORDPRESS_DB_USER
      value: "wp"
    - name: WORDPRESS_DB_PASSWORD
      value: "patata"
    - name: WORDPRESS_DB_NAME
      value: "wp"
  