pipeline {
    agent any

    environment {
        PROJECT_PATH = '03-CICD/Entrega_CICD/Ejercicios_Jenkins/ejercicio_1/jenkins-resources/calculator'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                echo 'Listing directory contents and current working directory...'
                dir("${env.PROJECT_PATH}") {
                    sh 'ls -l'
                }
                sh 'pwd'
            }
        }

        stage('Prepare Environment') {
            steps {
                echo 'Setting permissions for gradlew...'
                dir("${env.PROJECT_PATH}") {
                    sh 'chmod +x ./gradlew'
                }
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling source code...'
                dir("${env.PROJECT_PATH}") {
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running unit tests...'
                dir("${env.PROJECT_PATH}") {
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
