pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                echo 'Listing directory contents...'
                sh 'ls -l ./'
                sh 'pwd'
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling source code...'
                sh './gradlew compileJava'
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running unit tests...'
                sh './gradlew test'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
