FROM node:18-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

COPY . .


EXPOSE 3000

RUN ["npm", "install"]

RUN echo Running tests && \
    npm test

CMD ["npm", "start"]